apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: task-management-service
spec:
  selector:
    app: task-management
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: task-management
spec:
  selector:
    matchLabels:
      app: task-management
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: task-management
    spec:
      containers:
        - name: task-management
          image: task-management # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: regcred